name: publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: setup
        uses: actions/checkout@v4

      - name: java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: github

      - name: version update
        run: mvn --batch-mode versions:set -DnewVersion=${{ github.ref_name }}

      - name: publish
        run: mvn --batch-mode deploy source:jar
        env:
          GITHUB_TOKEN: ${{ github.token }}
